## Chapter 2

Инициализация интерактвиного сеанса Tensorflow

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.6.2'

In [4]:
#from version v2.x you should use this for activate version
import tensorflow.compat.v1 as tfc

In [5]:
sess = tfc.InteractiveSession()

In [10]:
# создание тензора нулей
a = tf.zeros(2)

In [16]:
# возрат значения
print(a.numpy())

[0. 0.]


In [17]:
# выведение матрицы с единицами
b = tf.ones((2, 2, 2))
b.numpy()

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [18]:
# заполнение тензоров произвольными значениями
c = tf.fill((2, 2), value=5.)
c.numpy()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [19]:
# создание константных тензоров (не должны изменяться во время выполнения программ)
a = tf.constant(3)
a.numpy()

3

In [22]:
# отбор случайных значений для тензора из нормального распределения
b = tf.random.normal((2, 2), mean=0, stddev=1)
b.numpy()

array([[-0.8828074,  1.5494524],
       [ 0.3921401, -1.229013 ]], dtype=float32)

In [23]:
# отбор случайных значений для тензора из равномерного распределения
a = tf.random.uniform((2, 2), minval=-2, maxval=2)
a.numpy()

array([[-0.22129059,  0.85585594],
       [-0.754931  ,  1.1418471 ]], dtype=float32)

In [24]:
# сложение тензоров
c = tf.ones((2, 2))
d = tf.ones((2, 2))
e = c + d
e.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>>

In [25]:
f = 2 * e
f.numpy()

array([[4., 4.],
       [4., 4.]], dtype=float32)

In [27]:
# поэлементное умножение (при умножении тензоров мы получаем не матричное умножение, а поэлементное)
c = tf.fill((2, 2), 2.)
d = tf.fill((2, 2), 7.)
e = c * d
e.numpy()

array([[14., 14.],
       [14., 14.]], dtype=float32)

In [32]:
# создание единичной матрицы - это квадратная матрица, элементы которой равны 0 везде, кроме главной диагонали, где они равны 1
tf.eye(4).numpy()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [36]:
# tf.range(начало, граница(не включительно), дельта)
r = tf.range(1, 5, 1)
r.numpy()

array([1, 2, 3, 4], dtype=int32)

In [35]:
# диагональная матрица - так же являются ненулевыми по диагонали, но по диагонали могут быть произвольные значения
d = tf.linalg.diag(r)
d.numpy()

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]], dtype=int32)

In [38]:
# получение транспонированной матрицы
a = tf.ones((2, 3))
a.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [39]:
at = tf.transpose(a)
at.numpy()

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [40]:
# выполнение матричного умножения
b = tf.ones((3, 4))
c = tf.matmul(a, b)
c.numpy()

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)

In [41]:
# смена типа данных тензора
a = tf.ones((2, 2), dtype=tf.int32)
a.numpy()

array([[1, 1],
       [1, 1]], dtype=int32)

In [45]:
b = tf.cast(a, tf.float32)
b.numpy()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [46]:
# манипуляция с формами тензоров. reshape - позволяет конвертировать тензоры в тензоры другой формы
a = tf.ones(8)
a.numpy()

array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [48]:
b = tf.reshape(a, (4, 2))
b.numpy()

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [49]:
c = tf.reshape(a, (2, 2, 2))
c.numpy()

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [50]:
# получение формы тензора
a = tf.ones(2)
a.get_shape()

TensorShape([2])

In [53]:
# expand_dims добавляет в тензор новую размерность размера 1 
b = tf.expand_dims(a, 0)
b.get_shape()

TensorShape([1, 2])

In [54]:
b.numpy()

array([[1., 1.]], dtype=float32)

In [55]:
c = tf.expand_dims(a, 1)
c.get_shape()

TensorShape([2, 1])

In [56]:
c.numpy()

array([[1.],
       [1.]], dtype=float32)

In [57]:
# squeeze удаляет из тензора все размерности размера 1, превращая например векторк-строку 2 ранга в вектор 1-го ранга
d = tf.squeeze(b)
d.get_shape()

TensorShape([2])

In [59]:
d.numpy()

array([1., 1.], dtype=float32)

In [60]:
# примеры транслирования - добавления к матрицам тензорной системы вектора разного размера
a = tf.ones((2, 2))
b = tf.range(0, 2, 1, dtype=tf.float32) 
# если не задать явно тип, то будет ошибка, т.к. tensorflow не выполняет неявное приведение типов
b.numpy()

array([0., 1.], dtype=float32)

In [61]:
c = a + b
c.numpy()

array([[1., 2.],
       [1., 2.]], dtype=float32)

In [62]:
# TensorFlow выполняет только декларативное сложение
a = tf.constant(3)
b = tf.constant(4)
c = a + b
c

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [63]:
c.numpy()

7

In [80]:
# обработка сеансов явным образом
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x
sess = tfc.Session()
a = tf.ones((2, 2))
b = tf.matmul(a, a)

In [81]:
print(sess.run(b))

[[2. 2.]
 [2. 2.]]


In [91]:
# объекты-переменные Variable служат контейнером для тензоров
a = tf.Variable(tf.ones((2, 2)))
a

<tf.Variable 'Variable_4:0' shape=(2, 2) dtype=float32>

In [98]:
# tf.global_variables_initializer() - инициализирует все переменные для расчета. более не используется
init_op = tf.local_variables_initializer()
sess.run(init_op)
print(sess.run(a))

AttributeError: module 'tensorflow' has no attribute 'local_variables_initializer'

In [99]:
# при помощи функции assign мы можем обновить значение существующей переменной
tf.compat.v1.disable_eager_execution() # need to disable eager in TF2.x
sess = tfc.Session()
sess.run(a.assign(tf.zeros((2, 2))))
sess.run(a)

array([[0., 0.],
       [0., 0.]], dtype=float32)

## Chapter 3